branches:
  - master

pipeline:
  build-docs:
    image: node
    commands:
      - yarn install
      - yarn build:docs

  build-system:
    image: node
    commands:
      - yarn install
      - yarn build:system

  publish:
    image: plugins/gh-pages:1
    secrets: [github_username, github_password]
    pages_directory: dist/docs
    when:
      event: [push]
